version: '3'
services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "86:80"
    depends_on:
      - laravel-app
    networks:
      - app-network

  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: laravel-app
  ports:
      - "9000:9000"
    volumes:
      - ./storage:/var/www/html/storage
    networks:
      - app-network

networks:
  app-network:
    driver: bridge