version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "86:80"  # Mappe le port 80 du conteneur au port 86 de l'hôte pour le serveur Laravel
    volumes:
      - .:/var/www/html
    environment:
      - MIGRATE_ON_START=true  # Définit la variable d'environnement pour les migrations
    command: php artisan serve --host=0.0.0.0 --port=80  # Utiliser le port 80 dans le conteneur pour la communication avec Nginx
    networks:
      - laravel_network

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    ports:
      - "87:81"
      - "88:80"   # Port HTTP
      - "447:443" # Port HTTPS
    environment:
      - MYSQL_HOST=159.223.206.185
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1XinI8x2ApWrrx9EvHwSoGk9RDXztlYNk9H47xQWaGbXeNKE7ET0bt5elX7n4Gvp
      - MYSQL_DATABASE=npm
    volumes:
      - nginx-proxy-manager-data:/data
      - nginx-proxy-manager-letsencrypt:/etc/letsencrypt
    depends_on:
      - mysqldb
    mysqldb:
      container_name: mysql_db
      image: jc21/mariadb-aria
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: "1XinI8x2ApWrrx9EvHwSoGk9RDXztlYNk9H47xQWaGbXeNKE7ET0bt5elX7n4Gvp" # use secret instead
        MYSQL_AUTH_PLUGIN: mysql_native_password
        MYSQL_PORT: 3307
        MYSQL_DATABASE: "nginx-manager"
        MYSQL_USER: "nginx"
        MYSQL_PASSWORD: "1XinI8x2ApWrrx9EvHwSoGk9RDXztlYNk9H47xQWaGbXeNKE7ET0bt5elX7n4Gvp" # use secret instead
      ports:
        - "3307:3306"
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  nginx-proxy-manager-data:
  nginx-proxy-manager-letsencrypt:
