version: '3.8'

services:
  # Service PHP-FPM
  app:
    build:
      context: .
      target: laravel-app
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel

  # Service Nginx
  webserver:
    build:
      context: .
      target: nginx
    container_name: nginx-webserver
    ports:
      - "86:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
