version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "86:80"
    volumes:
      - .:/var/www/html
    command: >
      /bin/sh -c "
      echo '
      server {
      listen 80;
      server_name localhost;

      root /var/www/html/public;
      index index.php index.html index.htm;

      location / {
          try_files $uri $uri/ /index.php?$query_string;
      }

      location ~ \.php$ {
          include fastcgi_params;
          fastcgi_pass laravel-app:9000;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_buffers 16 16k;
          fastcgi_buffer_size 32k;
      }

      location ~ /\.ht {
          deny all;
      }
      }
      ' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;' "
    networks:
      - laravel_network
    depends_on:
      - laravel-app


networks:
  laravel_network:
    driver: bridge
