version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "86:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
