version: '3.8'

services:
  app:
    build:
      context: . # This assumes the Dockerfile is in the same directory
      dockerfile: Dockerfile # Optional if your Dockerfile is named 'Dockerfile'
    image: laravel-app # This will tag the built image as 'laravel-app'
    command: ["php", "/var/www/html/artisan", "schedule:work"]
    environment:
      - PHP_OPCACHE_ENABLE=1
    ports:
      - "86:80" # Map port 80 on the host to port 80 in the container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
