version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-fpm-container
    expose:
      - 9000
    networks:
      - app-network

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-container
    ports:
      - "86:80"
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
