version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "86:80"  # Map port 86 on the host to port 80 on the container
      - "9001:9000" # Map port 9000 on the host to port 9000 on the container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
