version: '3'
services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "86:80" # Exposes port 86 on the host to port 80 on the container
    depends_on:
      - laravel-app
    networks:
      - app-network

  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: laravel-app
    ports:
      - "8007:8000" # Exposes port 8000 on the host to port 8000 on the container
      - "9000:9000" # Exposes port 8000 on the host to port 8000 on the container
    command: php artisan serve --host=0.0.0.0 --port=8007
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
