version: '3'
services:

  laravel-app:
    build:
      context: .
      dockerfile: laravel.Dockerfile
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - laravel-app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge