version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "86:80"  # Mappe le port 80 du conteneur au port 8000 de l'hôte
    volumes:
      - .:/var/www/html
    environment:
      - MIGRATE_ON_START=true  # Définit la variable d'environnement pour les migrations
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
