version: '3'
services:

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - laravel-app
    networks:
      - app-network

  laravel-app:
    build:
      context: .
      dockerfile: laravel.Dockerfile
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    volumes:
      - .:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge