version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app:latest
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - .:/app
    environment:
      - APP_ENV=production
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
