version: '3'
services:

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    ports:
      - "86:80"
    depends_on:
      - laravel-app
    networks:
      - app-network

  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: laravel-app
      ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge