version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    environment:
      - PHP_OPCACHE_ENABLE=1
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql
    working_dir: /var/www/html
    command: php-fpm
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "86:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - app
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
