version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "86:80"  # Mappe le port 80 du conteneur au port 86 de l'hôte pour le serveur Laravel
    volumes:
      - .:/var/www/html
    environment:
      - MIGRATE_ON_START=true  # Définit la variable d'environnement pour les migrations
    command: php artisan serve --host=0.0.0.0 --port=86  # Utiliser le port 80 dans le conteneur pour la communication avec Nginx
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
